[package]
name = "disk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libparted = "0.1"
libparted-sys = "0.3"
tracing = "0.1"
fancy-regex = "0.13"
thiserror = "1.0"
disk-types = "0.1"
